name: Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
       
    - name: Build and test
      run: mvn clean verify

    - name: Archive Serenity report
      uses: actions/upload-artifact@v4
      with:
        name: serenity-report
        path: target/site/serenity
